# Generated by Django 5.1.3 on 2024-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='reservation_date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reservation_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.IntegerField(default=1),
        ),
    ]
